[@ww.textfield labelKey='advancedinstaller.root_path' name='root_path' required='true'/]
[@ww.textfield labelKey='advancedinstaller.aip_path' name='aip_path' required='true'/]
[@ww.textfield labelKey='advancedinstaller.aip_build' name='aip_build' required='false'/]
[@ww.textfield labelKey='advancedinstaller.output_file' name='output_file' required='false'/]
[@ww.textfield labelKey='advancedinstaller.output_folder' name='output_folder' required='false'/]
[@ww.textarea  labelKey='advancedinstaller.commands' name='commands' required='false'/]
[@ww.checkbox  labelKey='advancedinstaller.digital_signature' name='digital_signature' toggle='true'/]