[@ww.label labelKey='advancedinstaller.root_path' name='root_path'/]
[@ww.label labelKey='advancedinstaller.aip_path' name='aip_path'/]
[@ww.label labelKey='advancedinstaller.aip_build' name='aip_build'/]
[@ww.label labelKey='advancedinstaller.output_file' name='output_file'/]
[@ww.label labelKey='advancedinstaller.output_folder' name='output_folder'/]
[@ww.label labelKey='advancedinstaller.commands' name='commands'/]
[@ww.label labelKey='advancedinstaller.digital_signature' name='digital_signature'/]